### PR TITLE
Re-order Travis jobs by Python version descending

### PR DESCRIPTION
**Pull request by jayvdb**
Sits on top of https://github.com/di/pytest-reqs/pull/19

### CODE REVIEW

**Comment by di** [comment]
Hi @jayvdb, can you explain why the order of the Travis jobs needs to be changed?

**Comment by jayvdb** [comment]
I find it more helpful to see results of recent releases first, but this is your choice of course.

Let me know if you want me to rebase it.  Otherwise close

**Comment by di** [comment]
Sure, please rebase.

**Comment by jayvdb** [comment]
Also I remember, the py37 job is faster, so getting it started first will result in first positive confirmation of green build happening even sooner.  And this is a rather heavy build matrix due to version testing, so seeing green sooner is nice ;-)

will rebase shortly -- finishing another one first.

**Comment by jayvdb** [comment]
Oh, and the order change was so that the flakes job was first

**Comment by jayvdb** [comment]
It looks like the flake8 testenv isnt being run any more on Travis CI.

**Pull request merged**
